### ISSUE TITLE
Build error on new Macroquad version

### ISSUE THREAD

**Issue by Zageron** [optozorax/egui-macroquad#14] opened 2022-01-31 22:23 UTC
```rust
error: failed to select a version for `miniquad`.
    ... required by package `egui-miniquad v0.8.0`
    ... which satisfies dependency `egui-miniquad = "^0.8.0"` of package `egui-macroquad v0.8.0`
    ... which satisfies dependency `egui-macroquad = "^0.8.0"` of package `rrr-render v0.0.1 (L:\git\flashflashrevolution\games\rrr\crates\render)`
versions that meet the requirements `=0.3.0-alpha.43` are: 0.3.0-alpha.43

all possible versions conflict with previously selected packages.

  previously selected package `miniquad v0.3.0-alpha.42`
    ... which satisfies dependency `miniquad = "=0.3.0-alpha.42"` of package `macroquad v0.3.13`
    ... which satisfies dependency `macroquad = "^0.3.13"` of package `rrr-render v0.0.1 (L:\git\flashflashrevolution\games\rrr\crates\render)`

failed to select a version for `miniquad` which could resolve this conflict
```

```toml
[dependencies]
rrr = { path = "../rrr", version = "0.0.1" }
egui = "0.16.1"
egui-macroquad = "0.8.0"
macroquad = { version = "0.3.13", default-features = false }
```

The change is macroquad `0.3.6` to `0.3.13`.
I'm not sure if this is a egui dependency declaration problem, or a macroquad/miniquad one, or if it's me.

**Comment by caspianmerlin** [comment] 2022-02-08 19:31
Same issue here as well.

**Comment by optozorax** [comment] 2022-02-09 12:34
Hi, sorry for the late answer. I think the problem is in the latest `macroquad` (https://github.com/not-fl3/macroquad/blob/master/Cargo.toml#L29) which requires exactly `miniquad = 42`, but `egui-miniquad` (https://github.com/not-fl3/egui-miniquad/blob/master/Cargo.toml#L23) requires exactly `miniquad = 43`. So, there is the conflict. At the time I made a release, everything worked.

I will try make an issue in the `macroquad` repo.

**Comment by optozorax** [comment] 2022-02-28 19:14
Fixed in new version.

**Closed by optozorax** 2022-02-28 19:14 UTC
